# Feature Selection
2nd round of pre-processing involves dimensionality reduction by using cluster variables by (Hämäläinen, R., de Wever, B., Nissinen, K., & Cincinnato, S. (2017). Understanding adults’ strong problem-solving skills based on PIAAC. Journal of Workplace Learning, 29(7–8), 537–553. https://doi.org/10.1108/JWL-05-2016-0032)

socio-demographic cluster:
- age, measured continuously but categorized in ten-year spans;
- occupational status, differentiating between elementary, semi-skilled blue-collar, semi-skilled white collar and skilled occupations;
- gender;
- cultural capital as measured by the number of owned books, namely, more or less than 100 books;
- cultural capital as measured by parents’ educational level, differentiating between less than upper secondary education, upper secondary education and higher education;
- cultural background as measured by language spoken at home, differentiating between native and non-native speakers;
- subjective health.

workplace skill-use and learning cluster:
- numeracy skill-use;
- ICT skill-use;
- reading skill-use;
- writing skill-use;
-  informal learning opportunities;
- (non-)formal learning opportunities as measured by participation in adult education and training (AET) for job-related reasons;
- employment type, differentiating between the self-employed and employees; and
- job position, differentiating between supervisors and others

everyday-life skill use and learning cluster:
- numeracy skill-use;
- ICT skill-use;
- reading skill-use;
- writing skill-use; and
- (non-)formal learning opportunities as measured by participation in AET for non-job-related reasons.

In [18]:
import pandas  as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Loading data

In [19]:
codebook = pd.read_excel('PIAAC\Cycle 1\International Codebook_PIAAC Public-use File (PUF) Variables and Values.xlsx')
df = pd.read_csv('data_cb.csv')

print(df.shape)
df.head()

C:\Users\Anis\AppData\Local\Temp\ipykernel_17996\3174940704.py:2: DtypeWarning: Columns (3,14,16,17,292,293,294,328,331,332,333,334,335,336,339,383,384,412,437,438,439,441,442,443,445,446,447,449,450,451,453,454,455,457,458,459,1303,1317) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data_cb.csv')

(16422, 1327)

,CNTRYID,CNTRYID_E,SEQID,AGE_R,GENDER_R,DISP_CIBQ,DISP_MAIN,DISP_MAINWRC,A_N01_T,B_Q01a,...,READHOME,READHOME_WLE_CA,READWORK,READWORK_WLE_CA,TASKDISC,TASKDISC_WLE_CA,WRITHOME,WRITHOME_WLE_CA,WRITWORK,WRITWORK_WLE_CA
0,Japan,Japan,2,48,Male,Complete,Complete,Not stated or inferred,Male,"ISCED 5A, bachelor degree",...,1.642143,More than 20% to 40%,2.5055051847,More than 60% to 80%,3.4173329532,More than 80%,1.7261603903,More than 20% to 40%,2.3759603464,More than 60% to 80%
1,Japan,Japan,3,47,Male,Complete,Complete,Not stated or inferred,Male,"ISCED 5A, bachelor degree",...,2.489266,More than 60% to 80%,2.2354666313,More than 40% to 60%,4.3041123844,More than 80%,2.4388697484,More than 40% to 60%,2.9854125867,More than 80%
2,Japan,Japan,4,58,Male,Complete,Complete,Not stated or inferred,Male,"ISCED 5A, bachelor degree",...,3.228828,More than 80%,2.6327402619,More than 60% to 80%,2.3366330654,More than 60% to 80%,1.0337279555,Lowest to 20%,2.7324281757,More than 60% to 80%
3,Japan,Japan,5,29,Female,Complete,Complete,Not stated or inferred,Female,ISCED 5B,...,3.733989,More than 80%,All zero response,Not stated or inferred,All zero response,Not stated or inferred,2.9494592794,More than 80%,All zero response,Not stated or inferred
4,Japan,Japan,8,48,Female,Complete,Complete,Not stated or inferred,Female,ISCED 2,...,2.129691,More than 40% to 60%,All zero response,Not stated or inferred,All zero response,Not stated or inferred,2.2227701051,More than 40% to 60%,All zero response,Not stated or inferred

## Variables to keep

In [20]:
# socio-demographic cluster:
# - AGE_R           age
# - GENDER_R        gender
# - LNG_HOME        Language most often spoken at home - Respondent (ISO 639-2/T) (coded)
# - NATIVELANG      Test language same as native language (derived)
# - NATIVESPEAKER   Respondent is a native speaker (DERIVED BY CAPI)
# - J_Q06b        Background - Mother/female guardian - Highest level of education
# - J_Q07b        Background - Father/male guardian - Highest level of education
# - I_Q08           About yourself - Health - State
# - J_Q04a          Background - Born in country

demographic_var = ['CNTRYID', 'AGE_R', 'GENDER_R', 'LNG_HOME', 'NATIVELANG', 'NATIVESPEAKER', 'J_Q06b', 'J_Q07b', 'I_Q08', 'J_Q04a']
len(demographic_var)

10

In [21]:
# education and work
# - C_Q07           Current status/work history - Subjective status
# - C_D06           Current status/work history - Current - Paid job or family business (DERIVED BY CAPI)
# - B_Q01a          highest education
# - B_Q01a3         Education - Highest qualification - Level of foreign qualification
# - B_Q01b          Education - Highest qualification - Area of study 

# - D_Q12a          Current work - Requirements - Education level
# - B_Q05c	        Education - Formal qualification - Reason job related
# - B_Q10c	        Education - Formal qualification - Employed - Useful for job

# - D_Q14	        Current work - Job satisfaction

# - ISCOSKIL4       Occupational classification of respondent's job (4 skill based categories), last or current (derived)
# - ISCO1C          Occupational classification of respondent's job at 1-digit level (ISCO 2008), current job (derived)
# - ISCO2C          Occupational classification of respondent's job at 2-digit level (ISCO 2008), current job (derived)

# - D_Q10           Current work - Hours/week
# - D_Q03           Current work - Economic sector
# - D_Q04           Current work - Employee or self-employed

# - D_Q07a          Current work - Employees working for you
# - D_Q07b          Current work - Employees working for you - Count
# - D_Q08a          Current work - Managing other employees
# - D_Q08b          Current work - Managing other employees - Count

# - VET             Respondent's highest level of education obtained is vocationally oriented (derived, ISCED3 and 4 only)
# - NFEHRS          Number of hours of participation in non-formal education (derived)

eduwork_var = ['CNTRYID', 'C_Q07', 'C_D06', 'B_Q01a', 'B_Q01a3', 'B_Q01b', 'D_Q12a', 'B_Q05c', 'B_Q10c', 'D_Q14', 'ISCOSKIL4', 'ISCO1C', 'ISCO2C', 'D_Q10', 'D_Q03', 'D_Q04', 'D_Q07a', 'D_Q07b', 'D_Q08a', 'D_Q08b', 'VET', 'NFEHRS']
len(eduwork_var)

22

In [22]:
# workplace skill-use and learning cluster:
# - Skill use work: every F_ variable
# - more details vals = codebook[codebook['Name'].str.startswith('G_') & codebook['Label'].str.contains('ICT')]
# - ICTWORK     Index of use of ICT skills at work (derived)
# - NFEHRSJR      Number of hours of participation in non-formal education for job-related reasons (derived)

worksl_var = ['CNTRYID', 'ICTWORK', 'NFEHRSJR']

worksl_var.extend(codebook.loc[codebook['Name'].str.startswith('F_'), 'Name'].tolist())
worksl_var.extend(codebook.loc[codebook['Name'].str.startswith('G_') & codebook['Label'].str.contains('ICT'), 'Name'].tolist())

len(worksl_var)

31

In [23]:
# everyday-life skill use and learning cluster:
# - codebook[codebook['Name'].str.startswith('H_') & codebook['Label'].str.contains('ICT')]
# - learning strategies = codebook[codebook['Name'].str.startswith('I_') & codebook['Label'].str.contains('Learning')]
# - ICTHOME     Index of use of ICT skills at home (derived)
# - NFEHRSNJR     Number of hours of participation in non-formal education for non-job-related reasons (derived)

lifesl_var = ['CNTRYID', 'ICTHOME', 'NFEHRSNJR']

lifesl_var.extend(codebook.loc[codebook['Name'].str.startswith('H_') & codebook['Label'].str.contains('ICT'), 'Name'].tolist())
lifesl_var.extend(codebook.loc[codebook['Name'].str.startswith('I_') & codebook['Label'].str.contains('Learning'), 'Name'].tolist())


len(lifesl_var)

18

In [24]:
pvpsl = []

pvpsl.extend(codebook.loc[codebook['Name'].str.startswith('PVPSL'), 'Name'].tolist())
pvpsl

['PVPSL1',
 'PVPSL2',
 'PVPSL3',
 'PVPSL4',
 'PVPSL5',
 'PVPSL6',
 'PVPSL7',
 'PVPSL8',
 'PVPSL9',
 'PVPSL10']

In [25]:
# Creating a dictionary to map the column names
vars = list(set(demographic_var + eduwork_var + worksl_var + lifesl_var + pvpsl))
vars_keep = [var for var in vars if not (var[0].isalpha() and var[1] == '_')]
vars_change = [var for var in vars if var[0].isalpha() and var[1] == '_']

vars_dict = {}

for i in vars_change:
    match = codebook.loc[codebook['Name'] == i, 'Label'].tolist()
    if match:
        vars_dict[i] = match[0]

print(len(vars))

88

In [26]:
demographic_mapped = [vars_dict.get(value, value) if value is not None else None for value in demographic_var]
eduwork_mapped = [vars_dict.get(value, value) if value is not None else None for value in eduwork_var]
worksl_mapped = [vars_dict.get(value, value) if value is not None else None for value in worksl_var]
lifesl_mapped = [vars_dict.get(value, value) if value is not None else None for value in lifesl_var]

print(len(demographic_mapped))
print(len(eduwork_mapped))
print(len(worksl_mapped))
print(len(lifesl_mapped))

10
22
31
18

## Column renaming

In [27]:
df_cols = df[vars].copy()

df_cols.rename(columns=vars_dict, inplace=True)
df_cols.to_csv('data_colrenamed.csv', index=False)

df_cols.head()

,Skill use work - ICT - Computer - How often - Programming language,ISCO1C,Skill use work - ICT - Computer - How often - Real-time discussions,Skill use work - How often - Organising own time,Skill use everyday life - ICT - Computer - How often - Word,Skill use work - How often - Planning others activities,PVPSL6,About yourself - Learning strategies - Attribute something new,ICTHOME,PVPSL8,...,Skill use work - ICT - Computer - How often - Word,Skill use work - How often - Presentations,Current work - Job satisfaction,Background - Mother/female guardian - Highest level of education,Current status/work history - Subjective status,Education - Highest qualification - Level,PVPSL4,PVPSL10,Skill use everyday life - ICT - Internet - How often - In order to better understand various issues,About yourself - Learning strategies - Get to the bottom of difficult things
0,At least once a week but not every day,Service workers and shop and market sales workers,Less than once a month,Every day,Less than once a week but at least once a month,Never,315.18911,To a high extent,2.021940093,296.26412,...,Every day,At least once a week but not every day,Satisfied,ISCED 3 (excluding 3C short) and 4,"Full-time employed (self-employed, employee)","ISCED 5A, bachelor degree",342.29315,318.98045,Less than once a week but at least once a month,To a high extent
1,Less than once a week but at least once a month,Professionals,Never,Every day,Never,Less than once a month,326.64999,To some extent,1.6462335216,273.53912,...,Less than once a month,Less than once a week but at least once a month,Dissatisfied,ISCED 3 (excluding 3C short) and 4,"Full-time employed (self-employed, employee)","ISCED 5A, bachelor degree",325.28718,296.98809,At least once a week but not every day,To a high extent
2,Never,"Legislators, senior officials and managers",At least once a week but not every day,Every day,At least once a week but not every day,At least once a week but not every day,285.41693,To some extent,3.4306571795,279.23163,...,Every day,At least once a week but not every day,Satisfied,"ISCED 1, 2, and 3C short","Full-time employed (self-employed, employee)","ISCED 5A, bachelor degree",316.26258,249.59748,Every day,Very little
3,Not stated or inferred,No paid work for past 5 years,Not stated or inferred,Not stated or inferred,Less than once a month,Not stated or inferred,330.86852,Very little,2.5492505885,310.46715,...,Not stated or inferred,Not stated or inferred,Not stated or inferred,ISCED 5 and 6,Fulfilling domestic tasks or looking after chi...,ISCED 5B,328.97784,323.93059,Every day,To some extent
4,Not stated or inferred,No paid work for past 5 years,Not stated or inferred,Not stated or inferred,Less than once a month,Not stated or inferred,326.36948,To some extent,0.9099452209,290.65124,...,Not stated or inferred,Not stated or inferred,Not stated or inferred,ISCED 3 (excluding 3C short) and 4,"Part-time employed (self-employed, employee)",ISCED 2,361.19844,316.76717,Less than once a month,Very little

# Sorting Workers

In [28]:
df_cols['Current status/work history - Current - Paid job or family business (DERIVED BY CAPI)'].value_counts()

Current status/work history - Current - Paid job or family business (DERIVED BY CAPI)
Yes, paid work one job or business                                                   10683
No                                                                                    4867
Yes, paid work more than one job or business or number of jobs/businesses missing      682
Yes, unpaid work for family business                                                   175
Not known                                                                               14
Not stated or inferred                                                                   1
Name: count, dtype: int64

In [29]:
df_workers = df_cols.copy()

w = 'Current status/work history - Current - Paid job or family business (DERIVED BY CAPI)'

df_workers = df_workers[(df_workers[w] == 'Yes, paid work one job or business') |
                    (df_workers[w] == 'Yes, paid work more than one job or business or number of jobs/businesses missing') |
                    (df_workers[w] == 'Yes, unpaid work for family business')]

df_workers.loc[df_workers['Current work - Employee or self-employed'] == 'Not stated or inferred', 'Current work - Employee or self-employed'] = 'Employee'

df_workers.shape

(11540, 88)

## Work Hours

In [30]:
df_hours = df_workers.copy()

df_hours = df_hours[df_hours['Current work - Hours/week'] != 'Not stated or inferred']
df_hours.shape

(11470, 88)

In [31]:
df_hours['Current work - Hours/week'] = pd.to_numeric(df_hours['Current work - Hours/week'], errors='coerce')
df_hours['WorkHours'] = 'Average'
df_hours['WorkHours_Difference'] = 0

# SEEING BY EACH COUNTRY
# jpn 40-42
# kor - 40-52
# kaz - 40-52
# sgp - 44-48

for index, row in df_hours.iterrows():
    cntry = row['CNTRYID']
    hours = row['Current work - Hours/week']
    
    if cntry != 'Singapore':
        if hours < 40:
            df_hours.at[index, 'WorkHours'] = 'Under Average'
            
            diff = hours - 40
            df_hours.at[index, 'WorkHours_Difference'] = diff

        elif hours > 42:
            if cntry == 'Japan':
                df_hours.at[index, 'WorkHours'] = 'Over Average'
                
                diff = hours - 42
                df_hours.at[index, 'WorkHours_Difference'] = diff
                
            elif hours > 52:
                df_hours.at[index, 'WorkHours'] = 'Over Average'
                
                diff = hours - 52
                df_hours.at[index, 'WorkHours_Difference'] = diff
                    
    elif cntry == 'Singapore':
        if hours > 48:
            df_hours.at[index, 'WorkHours'] = 'Over Average'
            
            diff = hours - 48
            df_hours.at[index, 'WorkHours_Difference'] = diff
            
        elif hours < 44:
            df_hours.at[index, 'WorkHours'] = 'Under Average'
            
            diff = hours - 44
            df_hours.at[index, 'WorkHours_Difference'] = diff

## Qualification Mismatch
Work requirement is not equal to highest educational attainment

In [32]:
iscad_level_mapping = {
    'No formal qualification or below ISCED 1': 1,
    'ISCED 1': 2,
    'ISCED 2': 3,
    'ISCED 3C shorter than 2 years': 4,
    'ISCED 3A-B': 5,
    'ISCED 3C 2 years or more': 6,
    'ISCED 3 (without distinction A-B-C, 2y+)': 7,
    'ISCED 4 (without distinction A-B-C)': 8,
    'ISCED 4A-B': 9,
    'ISCED 5A, bachelor degree': 10,
    'ISCED 5A, master degree': 11,
    'ISCED 5B': 12,
    'ISCED 6': 13,
}

isced3 = 4,5,6,7
isced4 = 8,9
isced5 = 10,11,12

def isced_mapping(row, checkcol, foreigncol = 'Education - Highest qualification - Level of foreign qualification'):
    if 'Foreign qualification' in row[checkcol]:
        return iscad_level_mapping.get(row[foreigncol], 0)
    else:
        return iscad_level_mapping.get(row[checkcol], 0)

In [33]:
df_edu = df_hours.copy()

df_edu['EduLevel'] = df_edu.apply(isced_mapping, axis=1, checkcol='Education - Highest qualification - Level')
df_edu['WorkLevel'] = df_edu.apply(isced_mapping, axis=1, checkcol='Current work - Requirements - Education level')

df_edu['Qualification_Comparision'] = 'Equal'
df_edu['Qualification_Status'] = 'Equal'

for index, row in df_edu.iterrows():
    diff = row['EduLevel'] - row['WorkLevel']
    
    if diff > 0:
        df_edu.at[index, 'Qualification_Comparision'] = 'Over by ' + str(diff) + ' level(s)'
        df_edu.at[index, 'Qualification_Status'] = 'Over'
    elif diff < 0:
        df_edu.at[index, 'Qualification_Comparision'] = 'Under by ' + str(abs(diff)) + ' level(s)'
        df_edu.at[index, 'Qualification_Status'] = 'Under'
    else:
        df_edu.at[index, 'Qualification_Comparision'] = 'Equal'
        df_edu.at[index, 'Qualification_Status'] = 'Equal'

items = ['EduLevel', 'WorkLevel', 'Qualification_Comparision', 'Qualification_Status', 'Education - Highest qualification - Level', 'Education - Highest qualification - Level of foreign qualification', 'Current work - Requirements - Education level']
display(df_edu.shape)
display(df_edu[items].head())

(11470, 94)

,EduLevel,WorkLevel,Qualification_Comparision,Qualification_Status,Education - Highest qualification - Level,Education - Highest qualification - Level of foreign qualification,Current work - Requirements - Education level
0,10,5,Over by 5 level(s),Over,"ISCED 5A, bachelor degree",Not stated or inferred,ISCED 3A-B
1,10,10,Equal,Equal,"ISCED 5A, bachelor degree",Not stated or inferred,"ISCED 5A, bachelor degree"
2,10,12,Under by 2 level(s),Under,"ISCED 5A, bachelor degree",Not stated or inferred,ISCED 5B
5,12,7,Over by 5 level(s),Over,ISCED 5B,Not stated or inferred,"ISCED 3 (without distinction A-B-C, 2y+)"
6,6,5,Over by 1 level(s),Over,ISCED 3C 2 years or more,Not stated or inferred,ISCED 3A-B

In [34]:
df_sorted = df_edu.drop(columns=['EduLevel', 'WorkLevel']).copy()
df_sorted.head()

,Skill use work - ICT - Computer - How often - Programming language,ISCO1C,Skill use work - ICT - Computer - How often - Real-time discussions,Skill use work - How often - Organising own time,Skill use everyday life - ICT - Computer - How often - Word,Skill use work - How often - Planning others activities,PVPSL6,About yourself - Learning strategies - Attribute something new,ICTHOME,PVPSL8,...,Current status/work history - Subjective status,Education - Highest qualification - Level,PVPSL4,PVPSL10,Skill use everyday life - ICT - Internet - How often - In order to better understand various issues,About yourself - Learning strategies - Get to the bottom of difficult things,WorkHours,WorkHours_Difference,Qualification_Comparision,Qualification_Status
0,At least once a week but not every day,Service workers and shop and market sales workers,Less than once a month,Every day,Less than once a week but at least once a month,Never,315.18911,To a high extent,2.021940093,296.26412,...,"Full-time employed (self-employed, employee)","ISCED 5A, bachelor degree",342.29315,318.98045,Less than once a week but at least once a month,To a high extent,Over Average,18,Over by 5 level(s),Over
1,Less than once a week but at least once a month,Professionals,Never,Every day,Never,Less than once a month,326.64999,To some extent,1.6462335216,273.53912,...,"Full-time employed (self-employed, employee)","ISCED 5A, bachelor degree",325.28718,296.98809,At least once a week but not every day,To a high extent,Over Average,8,Equal,Equal
2,Never,"Legislators, senior officials and managers",At least once a week but not every day,Every day,At least once a week but not every day,At least once a week but not every day,285.41693,To some extent,3.4306571795,279.23163,...,"Full-time employed (self-employed, employee)","ISCED 5A, bachelor degree",316.26258,249.59748,Every day,Very little,Over Average,18,Under by 2 level(s),Under
5,Never,Service workers and shop and market sales workers,Never,Less than once a month,Less than once a month,Never,332.55340,To a high extent,1.623672667,284.82134,...,"Part-time employed (self-employed, employee)",ISCED 5B,318.41257,325.03424,At least once a week but not every day,To some extent,Under Average,-15,Over by 5 level(s),Over
6,Never,Technicians and associate professionals,Never,Never,Never,Never,300.41854,To some extent,1.3654243174,290.70099,...,"Part-time employed (self-employed, employee)",ISCED 3C 2 years or more,307.69612,307.37447,Less than once a month,Very little,Under Average,-10,Over by 1 level(s),Over

## PV10 Performance

In [35]:
def pvpsl_score(x):
    if x >= 341:
        return 'Strong performer'
    elif x >= 291:
        return 'Moderate performer'
    elif x >= 241:
        return 'Weak performer'
    else:
        return 'At risk'

In [36]:
df_pvpsl = df_sorted.copy()

df_pvpsl['PVPSL_Performance'] = 'Moderate performer'

for index, row in df_pvpsl.iterrows():
    score = row[pvpsl[-1]]
    result = pvpsl_score(score)
    
    df_pvpsl.at[index, 'PVPSL_Performance'] = result
    
df_pvpsl['PVPSL_Performance'].unique()

array(['Moderate performer', 'Weak performer', 'At risk',
       'Strong performer'], dtype=object)

# Dtype fix

In [37]:
codebook

,Sequence in Dataset,Name,Label,Type,Level,Width,Decimals,Domain,Value scheme,Missing Scheme,Link to values
0,1,CNTRYID,"Country ID (ISO 3166, numeric)",Integer,Nominal,4,0,Sampling / weighting,"Participating country codes (ISO 3166, numeric)","Default (""blank""/Null/. only)",Values
1,2,CNTRYID_E,Participating country or sub-national entity c...,Integer,Nominal,4,0,Sampling / weighting,Participating country or sub-national entity s...,"Default (""blank""/Null/. only)",Values
2,3,SEQID,Sequential ID (randomly derived),Integer,Nominal,5,0,Not assigned,NaN,"Default (""blank""/Null/. only)",NaN
3,4,AGE_R,Person resolved age from BQ and QC check (deri...,Integer,Ratio,2,0,Sampling / weighting (derived),NaN,"Derived (""not stated"" only)",Values
4,5,GENDER_R,Person resolved gender from BQ and QC check (d...,Integer,Nominal,1,0,Sampling / weighting (derived),Gender,"Derived (""not stated"" only)",Values
...,...,...,...,...,...,...,...,...,...,...,...
1323,1324,SPFWT76,Final replicate weight (76),Numeric/floating point,Ratio,13,6,Sampling / weighting,NaN,"Default (""blank""/Null/. only)",NaN
1324,1325,SPFWT77,Final replicate weight (77),Numeric/floating point,Ratio,13,6,Sampling / weighting,NaN,"Default (""blank""/Null/. only)",NaN
1325,1326,SPFWT78,Final replicate weight (78),Numeric/floating point,Ratio,13,6,Sampling / weighting,NaN,"Default (""blank""/Null/. only)",NaN
1326,1327,SPFWT79,Final replicate weight (79),Numeric/floating point,Ratio,13,6,Sampling / weighting,NaN,"Default (""blank""/Null/. only)",NaN
1327,1328,SPFWT80,Final replicate weight (80),Numeric/floating point,Ratio,13,6,Sampling / weighting,NaN,"Default (""blank""/Null/. only)",NaN

In [38]:
df_num = df_pvpsl.copy()

df_num.select_dtypes(exclude='object')

,PVPSL6,PVPSL8,PVPSL9,PVPSL5,PVPSL1,PVPSL3,PVPSL7,PVPSL2,Current work - Hours/week,PVPSL4,PVPSL10,WorkHours_Difference
0,315.18911,296.26412,304.74757,320.26748,319.19725,308.83653,286.01639,300.98157,60,342.29315,318.98045,18
1,326.64999,273.53912,304.10690,307.90423,332.87631,316.14523,329.34613,303.48002,50,325.28718,296.98809,8
2,285.41693,279.23163,323.53888,293.13290,366.30684,318.85542,294.12734,323.62617,60,316.26258,249.59748,18
5,332.55340,284.82134,286.79526,300.92202,290.87807,310.88246,317.25004,331.96294,25,318.41257,325.03424,-15
6,300.41854,290.70099,292.65498,284.42722,324.20482,264.51513,294.82469,288.37479,30,307.69612,307.37447,-10
...,...,...,...,...,...,...,...,...,...,...,...,...
16412,180.35804,180.13456,154.97649,174.23964,178.49398,170.55828,220.03960,171.25707,44,206.40605,172.07546,0
16413,236.80046,209.95591,190.21406,237.55133,203.20370,212.81431,207.18062,201.47191,44,217.67521,224.81388,0
16414,215.25340,234.14435,241.03080,250.48670,239.64560,253.25730,267.84257,230.29050,60,234.11426,250.29909,12
16415,199.79572,208.68408,180.91977,190.70999,220.71721,203.63768,205.78928,198.42781,72,207.20378,203.04028,24
16420,145.78592,165.14347,181.09526,174.72456,206.94565,201.99786,175.40028,199.94382,40,171.36482,175.63626,-4

In [39]:
for col in df_num.select_dtypes(include='object').columns:
    print('Col: ', col, ' = ', df_num[col].unique())
    print()

Col:  Skill use work - ICT - Computer - How often - Programming language  =  ['At least once a week but not every day'
 'Less than once a week but at least once a month' 'Never' 'Every day'
 'Not stated or inferred' 'Less than once a month']

Col:  ISCO1C  =  ['Service workers and shop and market sales workers' 'Professionals'
 'Legislators, senior officials and managers'
 'Technicians and associate professionals'
 'Craft and related trades workers' 'Clerks'
 'Skilled agricultural and fishery workers'
 'Plant and machine operators and assemblers' 'Elementary occupations'
 'No paid work for past 5 years' 'Refused' "Don't know" 'Armed forces'
 'Not stated or inferred' 'Valid skip']

Col:  Skill use work - ICT - Computer - How often - Real-time discussions  =  ['Less than once a month' 'Never' 'At least once a week but not every day'
 'Not stated or inferred'
 'Less than once a week but at least once a month' 'Every day']

Col:  Skill use work - How often - Organising own time  =  ['Every day' 'Less than once a month' 'Never'
 'At least once a week but not every day'
 'Less than once a week but at least once a month'
 'Not stated or inferred']

Col:  Skill use everyday life - ICT - Computer - How often - Word  =  ['Less than once a week but at least once a month' 'Never'
 'At least once a week but not every day' 'Less than once a month'
 'Not stated or inferred' 'Every day']

Col:  Skill use work - How often - Planning others activities  =  ['Never' 'Less than once a month' 'At least once a week but not every day'
 'Less than once a week but at least once a month' 'Every day'
 'Not stated or inferred']

Col:  About yourself - Learning strategies - Attribute something new  =  ['To a high extent' 'To some extent' 'Not at all' 'Very little'
 'To a very high extent' 'Not stated or inferred']

Col:  ICTHOME  =  ['2.021940093' '1.6462335216' '3.4306571795' ... '2.26555' '1.8607'
 '2.9541']

Col:  Skill use work - ICT - Computer - How often - Spreadsheets  =  ['Every day' 'Less than once a week but at least once a month'
 'Less than once a month' 'At least once a week but not every day' 'Never'
 'Not stated or inferred']

Col:  NATIVELANG  =  ['Test language same as native language'
 'Test language not same as native language' 'Not stated or inferred']

Col:  Skill use work - How often - Influencing people  =  ['Less than once a week but at least once a month'
 'At least once a week but not every day' 'Every day' 'Never'
 'Less than once a month' 'Not stated or inferred']

Col:  Skill use work - ICT - Computer - Lack of skills affect career  =  ['Yes' 'No' 'Not stated or inferred']

Col:  Current work - Requirements - Education level  =  ['ISCED 3A-B' 'ISCED 5A, bachelor degree' 'ISCED 5B'
 'ISCED 3 (without distinction A-B-C, 2y+)' 'Not stated or inferred'
 'ISCED 4 (without distinction A-B-C)' 'ISCED 3C 2 years or more'
 'ISCED 3C shorter than 2 years' 'ISCED 2' 'ISCED 5A, master degree'
 'No formal qualification or below ISCED 1' 'ISCED 1' 'ISCED 6'
 'ISCED 4A-B']

Col:  Current work - Employee or self-employed  =  ['Employee' 'Self-employed']

Col:  Education - Highest qualification - Level of foreign qualification  =  ['Not stated or inferred' 'ISCED 5A, bachelor degree' 'ISCED 6'
 'ISCED 5A, master degree' 'ISCED 5B']

Col:  Skill use everyday life - ICT - Internet - How often - For mail  =  ['At least once a week but not every day' 'Every day'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Never' 'Not stated or inferred']

Col:  CNTRYID  =  ['Japan' 'Korea' 'Kazakhstan' 'Singapore']

Col:  Education - Highest qualification - Area of study  =  ['Social sciences, business and law'
 'Engineering, manufacturing and construction' 'General programmes'
 'Humanities, languages and arts' 'Not stated or inferred'
 'Health and welfare' 'Teacher training and education science'
 'Science, mathematics and computing' 'Agriculture and veterinary'
 'Services']

Col:  Current work - Employees working for you - Count  =  ['Not stated or inferred' '1 to 10 people' '11 to 50 people'
 '51 to 250 people' '251 to 1000 people' 'More than 1000 people']

Col:  About yourself - Learning strategies - Like learning new things  =  ['To some extent' 'To a high extent' 'Very little' 'To a very high extent'
 'Not at all' 'Not stated or inferred']

Col:  Skill use work - How often - Working physically for long  =  ['Less than once a week but at least once a month'
 'Less than once a month' 'Never' 'Every day'
 'At least once a week but not every day' 'Not stated or inferred']

Col:  About yourself - Learning strategies - Looking for additional info  =  ['To a very high extent' 'To a high extent' 'To some extent' 'Not at all'
 'Very little' 'Not stated or inferred']

Col:  Skill use work - Time cooperating with co-workers  =  ['Up to a quarter of the time' 'All of the time' 'Up to half of the time'
 'None of the time' 'More than half of the time' 'Not stated or inferred']

Col:  About yourself - Learning strategies - Figure out how different ideas fit together  =  ['To some extent' 'Very little' 'To a high extent' 'Not at all'
 'To a very high extent' 'Not stated or inferred']

Col:  Skill use work - Need more training  =  ['Yes' 'No' 'Not stated or inferred']

Col:  ICTWORK  =  ['3.6724015172' '1.7400325115' '2.7761300948' ... '0.69617' '1.91998'
 '1.35177']

Col:  GENDER_R  =  ['Male' 'Female']

Col:  Skill use work - How often - Teaching people  =  ['Less than once a month' 'Every day'
 'Less than once a week but at least once a month' 'Never'
 'At least once a week but not every day' 'Not stated or inferred']

Col:  Skill use work - How often - Sharing work-related info  =  ['At least once a week but not every day' 'Every day' 'Never'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred']

Col:  Current work - Employees working for you  =  ['Not stated or inferred' 'Yes' 'No']

Col:  Skill use work - How often - Selling  =  ['Less than once a week but at least once a month' 'Never'
 'At least once a week but not every day' 'Every day'
 'Less than once a month' 'Not stated or inferred']

Col:  About yourself - Learning strategies - Relate new ideas into real life  =  ['To a high extent' 'To some extent' 'Very little' 'To a very high extent'
 'Not at all' 'Not stated or inferred']

Col:  Skill use work - ICT - Internet - How often - For mail  =  ['Every day' 'Less than once a month'
 'Less than once a week but at least once a month'
 'Not stated or inferred' 'Never' 'At least once a week but not every day']

Col:  LNG_HOME  =  ['Japanese' 'Not stated or inferred' 'Korean' 'Thai' 'Zhuang; Chuang'
 'Russian' 'Kazakh' 'Tatar' 'Azerbaijani' 'Kirghiz; Kyrgyz'
 'Uighur; Uyghur' 'Turkish' 'Uzbek']

Col:  Skill use everyday life - ICT - Computer - How often - Spreadsheets  =  ['Less than once a week but at least once a month'
 'Less than once a month' 'At least once a week but not every day' 'Never'
 'Not stated or inferred' 'Every day']

Col:  NFEHRS  =  ['880' '24' '100' 'Not stated or inferred' '1000' '1200' '20' '32' '96'
 '160' '40' '1920' '5' '16' '56' '10' '2' '192' '80' '480' '21' '6' '4'
 '15' '8' '30' '120' '64' '7' '112' '200' '50' '104' '288' '3' '144' '12'
 '48' '600' '1600' '320' '9' '1400' '1640' '14' '800' '400' '720' '1' '18'
 '240' '1280' '1120' '90' '72' '960' '36' '128' '640' '66' '520' '1440'
 '17' '45' '280' '60' '140' '384' '65' '150' '820' '560' '224' '35' '300'
 '168' '83' '304' '26' '1760' '54' '352' '136' '101' '176' '86' '27' '22'
 '11' '1520' '47' '88' '70' '1680' '500' '74' '468' '184' '360' '132'
 '776' '768' '55' '1040' '138' '135' '680' '474' '840' '75' '416' '784'
 '34' '276' '57' '1344' '290' '201' '51' '99' '1800' '1080' '25' '968'
 '760' '256' '208' '357' '29' '1480' '134' '864' '250' '440' '248' '368'
 '344' '264' '1864' '1320' '206' '978' '93' '180' '1248' '210' '38' '118'
 '576' '108' '44' '816' '98' '87' '58' '94' '230' '84' '115' '700' '43'
 '448' '13' '832' '170' '130' '46' '992' '92' '152' '216' '158' '23' '552'
 '1456' '106' '432' '255' '528' '114' '76' '124' '49' '1152' '52' '59'
 '131' '77' '156' '39' '225' '365' '28' '234' '42' '1736' '750' '41' '116'
 '33' '53' '19']

Col:  ISCO2C  =  ['Personal service workers'
 'Information and communications technology professionals'
 'Administrative and commercial managers' 'Sales workers'
 'Health associate professionals'
 'Metal, machinery and related trades workers' 'Teaching professionals'
 'General and keyboard clerks'
 'Business and administration associate professionals'
 'Personal care workers' 'Market-oriented skilled agricultural workers'
 'Science and engineering associate professionals'
 'Handicraft and printing workers'
 'Stationary plant and machine operators'
 'Production and specialised services managers'
 'Labourers in mining, construction, manufacturing and transport'
 'Drivers and mobile plant operators'
 'Food processing, wood working, garment and other craft and related trades workers'
 'Health professionals' 'Legal, social and cultural professionals'
 'Legal, social, cultural and related associate professionals'
 'Business and administration professionals' 'Customer services clerks'
 'Protective services workers'
 'Chief executives, senior officials and legislators' 'Assemblers'
 'Hospitality, retail and other services managers'
 'Building and related trades workers, excluding electricians'
 'Electrical and electronic trades workers' 'Food preparation assistants'
 'Science and engineering professionals'
 'Numerical and material recording clerks'
 'Information and communications technicians'
 'Other clerical support workers' 'Cleaners and helpers'
 'No paid work for past 5 years' 'Refused' "Don't know"
 'Non-commissioned armed forces officers'
 'Armed forces occupations, other ranks'
 'Refuse workers and other elementary workers'
 'Agricultural, forestry and fishery labourers'
 'Market-oriented skilled forestry, fishery and hunting workers'
 'Commissioned armed forces officers' 'Professionals'
 'Not stated or inferred' 'Street and related sales and service workers'
 'Managers' 'Subsistence farmers, fishers, hunters and gatherers'
 'Technicians and associate professionals' 'Valid skip']

Col:  VET  =  ['Not stated or inferred' 'True' 'False']

Col:  Skill use work - ICT - Experience with computer in job  =  ['Yes' 'No']

Col:  Skill use everyday life - ICT - Computer - How often - Real-time discussions  =  ['Never' 'Less than once a week but at least once a month'
 'At least once a week but not every day' 'Less than once a month'
 'Not stated or inferred' 'Every day']

Col:  ISCOSKIL4  =  ['Semi-skilled white-collar occupations' 'Skilled occupations'
 'Semi-skilled blue-collar occupations' 'Elementary occupations'
 'Not stated or inferred']

Col:  Skill use work - ICT - Internet - How often - Conduct transactions  =  ['Every day' 'Never' 'Less than once a month' 'Not stated or inferred'
 'Less than once a week but at least once a month'
 'At least once a week but not every day']

Col:  NFEHRSJR  =  ['Not stated or inferred' '24' '0' '1200' '20' '32' '96' '160' '18' '40'
 '5' '12' '56' '2.5' '2' '192' '360' '5.25' '8' '16' '15' '30' '6' '90'
 '240' '64' '4' '10' '100' '112' '37.5' '78' '7.5' '80' '3' '144' '200'
 '48' '9' '1600' '410' '400' '36' '22.5' '0.75' '720' '2.25' '42' '60'
 '1280' '12.5' '600' '480' '7' '1.25' '120' '50' '130' '960' '8.5' '45'
 '1920' '128' '14' '800' '3.75' '900' '25' '140' '4.5' '72' '11.25' '216'
 '65' '150' '615' '0.5' '26' '35' '1440' '640' '83' '1.5' '105' '180'
 '320' '440' '1.75' '54' '352' '136' '750' '101' '86' '13.5' '5.5' '132'
 '288' '1140' '390' '47' '66' '3.5' '70' '27' '1' '1680' '300' '74' '28'
 '520' '280' '75' '468' '225' '184' '582' '55' '126' '260' '103.5' '135'
 '170' '118.5' '112.5' '22' '450' '392' '88' '25.5' '207' '14.25' '1344'
 '145' '150.75' '12.75' '49.5' '250' '67.5' '1800' '540' '168' '10.5'
 '6.75' '242' '104' '357' '41.25' '7.25' '560' '1000' '780' '34' '33.5'
 '21' '18.75' '62' '172' '510' '840' '264' '102' '466' '420' '270' '330'
 '1120' '680' '103' '416' '978' '256' '93' '6.5' '936' '26.25' '210'
 '28.5' '118' '81' '33' '612' '49' '84' '157.5' '87' '29' '17' '11' '115'
 '1760' '1080' '8.25' '700' '384' '52.5' '43' '448' '9.75' '125' '176'
 '1260' '16.5' '40.5' '38' '97.5' '34.5' '1350' '880' '92' '832' '114'
 '68' '39.5' '414' '432' '0.25' '191.25' '528' '124' '108' '11.5' '15.75'
 '1320' '20.25' '36.75' '32.25' '576' '1520' '59' '39' '32.75' '57.75'
 '760' '168.75' '365' '58.5' '187.5' '1736' '175.5' '17.5' '41' '52' '44'
 '220' '1248' '152' '13.25' '19']

Col:  Skill use work - How often - Using hands or fingers  =  ['Less than once a month' 'Never'
 'Less than once a week but at least once a month'
 'At least once a week but not every day' 'Every day'
 'Not stated or inferred']

Col:  AGE_R  =  [48 47 58 24 32 45 61 30 46 64 29 54 50 36 40 42 44 35 33 49 34 22 59 38
 56 20 55 23 19 25 52 26 53 39 37 57 62 27 43 18 41 28 63 21 31 60 51 65
 17 16 '36' '33' '48' '22' '27' '34' '24' '31' '21' '45' '29' '37' '28'
 '35' '25' '39' '26' '55' '32' '54' '47' '38' '17' '50'
 'Not stated or inferred']

Col:  Skill use work - ICT - Computer - Got the skills needed  =  ['Yes' 'No' 'Not stated or inferred']

Col:  Skill use work - How often - Negotiating with people  =  ['Less than once a week but at least once a month' 'Every day'
 'Less than once a month' 'Never' 'At least once a week but not every day'
 'Not stated or inferred']

Col:  Background - Born in country  =  ['Yes' 'No']

Col:  Current work - Managing other employees - Count  =  ['1 to 5 people' '6 to 10 people' 'Not stated or inferred'
 '11 to 24 people' '25 to 99 people' '100 or more people']

Col:  NATIVESPEAKER  =  ['Yes' 'No']

Col:  Current work - Economic sector  =  ['The private sector (for example a company)'
 'A non-profit organisation (for example a charity, professional association or religious organisation)'
 'The public sector (for example the local government or a state school)'
 'Not stated or inferred']

Col:  Skill use work - How often - Planning own activities  =  ['At least once a week but not every day' 'Every day' 'Never'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred']

Col:  Current status/work history - Current - Paid job or family business (DERIVED BY CAPI)  =  ['Yes, paid work one job or business'
 'Yes, paid work more than one job or business or number of jobs/businesses missing'
 'Yes, unpaid work for family business']

Col:  Skill use work - Problem solving - Simple problems  =  ['At least once a week but not every day' 'Every day' 'Never'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred']

Col:  Skill use work - How often - Advising people  =  ['Less than once a week but at least once a month' 'Every day'
 'Less than once a month' 'Never' 'At least once a week but not every day'
 'Not stated or inferred']

Col:  Skill use work - ICT - Computer - Level of computer use  =  ['Moderate' 'Complex' 'Straightforward' 'Not stated or inferred']

Col:  Skill use everyday life - ICT - Ever used computer  =  ['Not stated or inferred' 'Yes']

Col:  NFEHRSNJR  =  ['Not stated or inferred' '0' '100' '6' '4' '7.5' '80' '120' '15.75' '8'
 '5' '30' '240' '12' '12.5' '16' '18' '26' '2.5' '2' '1400' '1230' '800'
 '40' '2.25' '320' '0.75' '1.75' '14' '24' '20' '37.5' '200' '3.75' '160'
 '360' '66' '15' '390' '600' '480' '10' '8.5' '3' '56' '144' '1920' '1.25'
 '300' '75' '60' '180' '48' '1.5' '216' '384' '1440' '72' '205' '224' '78'
 '1200' '9' '112' '45' '304' '192' '4.5' '35' '1320' '5.25' '42' '32'
 '250' '36' '176' '13.5' '90' '16.5' '44' '96' '140' '380' '130' '168' '7'
 '22' '10.5' '1' '450' '900' '28' '11.25' '720' '50' '225' '1120' '352'
 '270' '150' '420' '194' '960' '780' '280' '34.5' '25' '400' '510' '355.5'
 '416' '392' '640' '840' '69' '0.5' '42.75' '145' '768' '50.25' '38.25'
 '49.5' '750' '22.5' '540' '3.5' '726' '760' '13.75' '21.75' '1480' '260'
 '102' '100.5' '648' '56.25' '186' '128' '184' '1600' '172' '170' '27'
 '34' '520' '1398' '1260' '990' '103' '210' '19.5' '312' '8.75' '9.5'
 '576' '810' '11' '204' '49' '52.5' '29' '47' '230' '63' '112.5' '115'
 '105' '2.75' '17.5' '3.25' '832' '1280' '125' '84' '5.5' '33.75' '32.5'
 '11.5' '64' '1350' '992' '880' '38' '68' '70' '118.5' '23' '138' '126'
 '135' '6.25' '63.75' '440' '6.75' '0.25' '12.25' '10.75' '54' '13'
 '98.25' '19.25' '17' '175.5' '62.5' '562.5' '114' '58.5' '67.5' '220'
 '39.75' '156']

Col:  Current work - Managing other employees  =  ['Yes' 'No' 'Not stated or inferred']

Col:  Skill use everyday life - ICT - Internet - How often - Conduct transactions  =  ['Never' 'Less than once a month' 'Every day'
 'Less than once a week but at least once a month'
 'At least once a week but not every day' 'Not stated or inferred']

Col:  About yourself - Health - State  =  ['Fair' 'Good' 'Very good' 'Excellent' 'Poor' 'Not stated or inferred']

Col:  Skill use work - Not challenged enough  =  ['Yes' 'Not stated or inferred' 'No']

Col:  Education - Formal qualification - Reason job related  =  ['Not stated or inferred' 'Yes' 'No']

Col:  Skill use work - Problem solving - Complex problems  =  ['Less than once a month' 'At least once a week but not every day'
 'Every day' 'Less than once a week but at least once a month' 'Never'
 'Not stated or inferred']

Col:  Skill use work - ICT - Internet - How often - Work related info  =  ['Every day' 'At least once a week but not every day'
 'Less than once a month'
 'Less than once a week but at least once a month'
 'Not stated or inferred' 'Never']

Col:  Skill use everyday life - ICT - Experience with computer everyday life  =  ['Yes' 'No' 'Not stated or inferred']

Col:  Skill use everyday life - ICT - Computer - How often - Programming language  =  ['Never' 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred' 'Every day'
 'At least once a week but not every day']

Col:  Education - Formal qualification - Employed - Useful for job  =  ['Not stated or inferred' 'Somewhat useful' 'Not useful at all'
 'Very useful' 'Moderately useful']

Col:  Background - Father/male guardian - Highest level of education  =  ['ISCED 3 (excluding 3C short) and 4' 'ISCED 5 and 6'
 'ISCED 1, 2, and 3C short' 'Not stated or inferred']

Col:  Skill use work - ICT - Computer - How often - Word  =  ['Every day' 'Less than once a month' 'Never'
 'At least once a week but not every day' 'Not stated or inferred'
 'Less than once a week but at least once a month']

Col:  Skill use work - How often - Presentations  =  ['At least once a week but not every day'
 'Less than once a week but at least once a month' 'Never' 'Every day'
 'Less than once a month' 'Not stated or inferred']

Col:  Current work - Job satisfaction  =  ['Satisfied' 'Dissatisfied' 'Neither satisfied nor dissatisfied'
 'Extremely satisfied' 'Extremely dissatisfied' 'Not stated or inferred']

Col:  Background - Mother/female guardian - Highest level of education  =  ['ISCED 3 (excluding 3C short) and 4' 'ISCED 1, 2, and 3C short'
 'ISCED 5 and 6' 'Not stated or inferred']

Col:  Current status/work history - Subjective status  =  ['Full-time employed (self-employed, employee)'
 'Part-time employed (self-employed, employee)' 'Pupil, student'
 'In retirement or early retirement' 'Other'
 'Fulfilling domestic tasks or looking after children/family' 'Unemployed'
 'Apprentice, internship' 'Permanently disabled'
 'In compulsory military or community service']

Col:  Education - Highest qualification - Level  =  ['ISCED 5A, bachelor degree' 'ISCED 5B' 'ISCED 3C 2 years or more'
 'ISCED 2' 'ISCED 3A-B' 'ISCED 3C shorter than 2 years'
 'ISCED 4 (without distinction A-B-C)' 'ISCED 5A, master degree'
 'Foreign qualification' 'ISCED 6'
 'ISCED 3 (without distinction A-B-C, 2y+)' 'Not stated or inferred'

## Learning Hours

In [40]:
nums = ['ICTWORK', 'NFEHRSJR', 'ICTHOME', 'NFEHRSNJR', 'AGE_R', 'NFEHRS']

count_per_column = df_num.apply(lambda col: col[col == 'Not stated or inferred'].count())

print('Not stated or inferred count')
for column, count in count_per_column.items():
    if count > 0 and column in nums:
        print(f"Column '{column}': {count} occurrences")
print()

print('All zero response count')
count_per_column = df_num.apply(lambda col: col[col == 'All zero response'].count())

for column, count in count_per_column.items():
    if count > 0 and column in nums:
        print(f"Column '{column}': {count} occurrences")
print()

print('Did not participate count')
count_per_column = df_num.apply(lambda col: col[col == 'Did not participate'].count())

for column, count in count_per_column.items():
    if count > 0 and column in nums:
        print(f"Column '{column}': {count} occurrences")

Not stated or inferred count
Column 'NFEHRS': 5224 occurrences
Column 'NFEHRSJR': 6704 occurrences
Column 'AGE_R': 3076 occurrences
Column 'NFEHRSNJR': 6704 occurrences

All zero response count
Column 'ICTHOME': 1334 occurrences
Column 'ICTWORK': 2747 occurrences

Did not participate count

In [41]:
df_num.loc[df_num['ICTWORK'] == 'All zero response', 'ICTWORK'] = 0
df_num.loc[df_num['ICTHOME'] == 'All zero response', 'ICTHOME'] = 0

for index, row in df_num.iterrows():
    hrs = row['NFEHRS']
    
    if hrs != 'Not stated or inferred':
        if row['NFEHRSJR'] == 'Not stated or inferred' and row['NFEHRSNJR'] == 'Not stated or inferred':
            df_num.at[index, 'NFEHRSJR'] = hrs
            df_num.at[index, 'NFEHRSNJR'] = hrs
        elif row['NFEHRSJR'] == 'Not stated or inferred':
            df_num.at[index, 'NFEHRSJR'] = hrs
        elif row['NFEHRSNJR'] == 'Not stated or inferred':
            df_num.at[index, 'NFEHRSNJR'] = hrs

for index, row in df_num.iterrows():
    hrs = row['NFEHRSJR']
    
    if hrs != 'Not stated or inferred':
        if row['NFEHRS'] == 'Not stated or inferred':
            df_num.at[index, 'NFEHRS'] = hrs

for index, row in df_num.iterrows():
    hrs = row['NFEHRSNJR']
    
    if hrs != 'Not stated or inferred':
        if row['NFEHRS'] == 'Not stated or inferred':
            df_num.at[index, 'NFEHRS'] = hrs

df_num['ICTWORK'] = df_num['ICTWORK'].astype(float)
df_num['ICTHOME'] = df_num['ICTHOME'].astype(float)

In [42]:
count_per_column = df_num.apply(lambda col: col[col == 'Not stated or inferred'].count())

print('Not stated or inferred count')
for column, count in count_per_column.items():
    if count > 0 and column in nums:
        print(f"Column '{column}': {count} occurrences")
print()

print('All zero response count')
count_per_column = df_num.apply(lambda col: col[col == 'All zero response'].count())

for column, count in count_per_column.items():
    if count > 0 and column in nums:
        print(f"Column '{column}': {count} occurrences")
print()

print('Did not participate count')
count_per_column = df_num.apply(lambda col: col[col == 'Did not participate'].count())

for column, count in count_per_column.items():
    if count > 0 and column in nums:
        print(f"Column '{column}': {count} occurrences")

Not stated or inferred count
Column 'NFEHRS': 5224 occurrences
Column 'NFEHRSJR': 5224 occurrences
Column 'AGE_R': 3076 occurrences
Column 'NFEHRSNJR': 5224 occurrences

All zero response count

Did not participate count

In [43]:
df_num.select_dtypes(exclude='object')

,PVPSL6,ICTHOME,PVPSL8,PVPSL9,ICTWORK,PVPSL5,PVPSL1,PVPSL3,PVPSL7,PVPSL2,Current work - Hours/week,PVPSL4,PVPSL10,WorkHours_Difference
0,315.18911,2.021940,296.26412,304.74757,3.672402,320.26748,319.19725,308.83653,286.01639,300.98157,60,342.29315,318.98045,18
1,326.64999,1.646234,273.53912,304.10690,1.740033,307.90423,332.87631,316.14523,329.34613,303.48002,50,325.28718,296.98809,8
2,285.41693,3.430657,279.23163,323.53888,2.776130,293.13290,366.30684,318.85542,294.12734,323.62617,60,316.26258,249.59748,18
5,332.55340,1.623673,284.82134,286.79526,0.902694,300.92202,290.87807,310.88246,317.25004,331.96294,25,318.41257,325.03424,-15
6,300.41854,1.365424,290.70099,292.65498,0.701393,284.42722,324.20482,264.51513,294.82469,288.37479,30,307.69612,307.37447,-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16412,180.35804,-0.776910,180.13456,154.97649,0.000000,174.23964,178.49398,170.55828,220.03960,171.25707,44,206.40605,172.07546,0
16413,236.80046,2.954100,209.95591,190.21406,1.621560,237.55133,203.20370,212.81431,207.18062,201.47191,44,217.67521,224.81388,0
16414,215.25340,1.062970,234.14435,241.03080,0.000000,250.48670,239.64560,253.25730,267.84257,230.29050,60,234.11426,250.29909,12
16415,199.79572,0.000000,208.68408,180.91977,0.000000,190.70999,220.71721,203.63768,205.78928,198.42781,72,207.20378,203.04028,24
16420,145.78592,0.000000,165.14347,181.09526,1.806100,174.72456,206.94565,201.99786,175.40028,199.94382,40,171.36482,175.63626,-4

In [44]:
for col in df_num.columns:
    print('Col: ', col, ' = ', df_num[col].dtypes)
    print(df_num[col].unique())
    print()

Col:  Skill use work - ICT - Computer - How often - Programming language  =  object
['At least once a week but not every day'
 'Less than once a week but at least once a month' 'Never' 'Every day'
 'Not stated or inferred' 'Less than once a month']

Col:  ISCO1C  =  object
['Service workers and shop and market sales workers' 'Professionals'
 'Legislators, senior officials and managers'
 'Technicians and associate professionals'
 'Craft and related trades workers' 'Clerks'
 'Skilled agricultural and fishery workers'
 'Plant and machine operators and assemblers' 'Elementary occupations'
 'No paid work for past 5 years' 'Refused' "Don't know" 'Armed forces'
 'Not stated or inferred' 'Valid skip']

Col:  Skill use work - ICT - Computer - How often - Real-time discussions  =  object
['Less than once a month' 'Never' 'At least once a week but not every day'
 'Not stated or inferred'
 'Less than once a week but at least once a month' 'Every day']

Col:  Skill use work - How often - Organising own time  =  object
['Every day' 'Less than once a month' 'Never'
 'At least once a week but not every day'
 'Less than once a week but at least once a month'
 'Not stated or inferred']

Col:  Skill use everyday life - ICT - Computer - How often - Word  =  object
['Less than once a week but at least once a month' 'Never'
 'At least once a week but not every day' 'Less than once a month'
 'Not stated or inferred' 'Every day']

Col:  Skill use work - How often - Planning others activities  =  object
['Never' 'Less than once a month' 'At least once a week but not every day'
 'Less than once a week but at least once a month' 'Every day'
 'Not stated or inferred']

Col:  PVPSL6  =  float64
[315.18911 326.64999 285.41693 ... 215.2534  199.79572 145.78592]

Col:  About yourself - Learning strategies - Attribute something new  =  object
['To a high extent' 'To some extent' 'Not at all' 'Very little'
 'To a very high extent' 'Not stated or inferred']

Col:  ICTHOME  =  float64
[2.02194009 1.64623352 3.43065718 ... 2.26555    1.8607     2.9541    ]

Col:  PVPSL8  =  float64
[296.26412 273.53912 279.23163 ... 234.14435 208.68408 165.14347]

Col:  Skill use work - ICT - Computer - How often - Spreadsheets  =  object
['Every day' 'Less than once a week but at least once a month'
 'Less than once a month' 'At least once a week but not every day' 'Never'
 'Not stated or inferred']

Col:  NATIVELANG  =  object
['Test language same as native language'
 'Test language not same as native language' 'Not stated or inferred']

Col:  Skill use work - How often - Influencing people  =  object
['Less than once a week but at least once a month'
 'At least once a week but not every day' 'Every day' 'Never'
 'Less than once a month' 'Not stated or inferred']

Col:  Skill use work - ICT - Computer - Lack of skills affect career  =  object
['Yes' 'No' 'Not stated or inferred']

Col:  Current work - Requirements - Education level  =  object
['ISCED 3A-B' 'ISCED 5A, bachelor degree' 'ISCED 5B'
 'ISCED 3 (without distinction A-B-C, 2y+)' 'Not stated or inferred'
 'ISCED 4 (without distinction A-B-C)' 'ISCED 3C 2 years or more'
 'ISCED 3C shorter than 2 years' 'ISCED 2' 'ISCED 5A, master degree'
 'No formal qualification or below ISCED 1' 'ISCED 1' 'ISCED 6'
 'ISCED 4A-B']

Col:  Current work - Employee or self-employed  =  object
['Employee' 'Self-employed']

Col:  Education - Highest qualification - Level of foreign qualification  =  object
['Not stated or inferred' 'ISCED 5A, bachelor degree' 'ISCED 6'
 'ISCED 5A, master degree' 'ISCED 5B']

Col:  Skill use everyday life - ICT - Internet - How often - For mail  =  object
['At least once a week but not every day' 'Every day'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Never' 'Not stated or inferred']

Col:  PVPSL9  =  float64
[304.74757 304.1069  323.53888 ... 241.0308  180.91977 181.09526]

Col:  CNTRYID  =  object
['Japan' 'Korea' 'Kazakhstan' 'Singapore']

Col:  Education - Highest qualification - Area of study  =  object
['Social sciences, business and law'
 'Engineering, manufacturing and construction' 'General programmes'
 'Humanities, languages and arts' 'Not stated or inferred'
 'Health and welfare' 'Teacher training and education science'
 'Science, mathematics and computing' 'Agriculture and veterinary'
 'Services']

Col:  Current work - Employees working for you - Count  =  object
['Not stated or inferred' '1 to 10 people' '11 to 50 people'
 '51 to 250 people' '251 to 1000 people' 'More than 1000 people']

Col:  About yourself - Learning strategies - Like learning new things  =  object
['To some extent' 'To a high extent' 'Very little' 'To a very high extent'
 'Not at all' 'Not stated or inferred']

Col:  Skill use work - How often - Working physically for long  =  object
['Less than once a week but at least once a month'
 'Less than once a month' 'Never' 'Every day'
 'At least once a week but not every day' 'Not stated or inferred']

Col:  About yourself - Learning strategies - Looking for additional info  =  object
['To a very high extent' 'To a high extent' 'To some extent' 'Not at all'
 'Very little' 'Not stated or inferred']

Col:  Skill use work - Time cooperating with co-workers  =  object
['Up to a quarter of the time' 'All of the time' 'Up to half of the time'
 'None of the time' 'More than half of the time' 'Not stated or inferred']

Col:  About yourself - Learning strategies - Figure out how different ideas fit together  =  object
['To some extent' 'Very little' 'To a high extent' 'Not at all'
 'To a very high extent' 'Not stated or inferred']

Col:  Skill use work - Need more training  =  object
['Yes' 'No' 'Not stated or inferred']

Col:  ICTWORK  =  float64
[3.67240152 1.74003251 2.77613009 ... 0.69617    1.91998    1.35177   ]

Col:  GENDER_R  =  object
['Male' 'Female']

Col:  Skill use work - How often - Teaching people  =  object
['Less than once a month' 'Every day'
 'Less than once a week but at least once a month' 'Never'
 'At least once a week but not every day' 'Not stated or inferred']

Col:  Skill use work - How often - Sharing work-related info  =  object
['At least once a week but not every day' 'Every day' 'Never'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred']

Col:  Current work - Employees working for you  =  object
['Not stated or inferred' 'Yes' 'No']

Col:  Skill use work - How often - Selling  =  object
['Less than once a week but at least once a month' 'Never'
 'At least once a week but not every day' 'Every day'
 'Less than once a month' 'Not stated or inferred']

Col:  About yourself - Learning strategies - Relate new ideas into real life  =  object
['To a high extent' 'To some extent' 'Very little' 'To a very high extent'
 'Not at all' 'Not stated or inferred']

Col:  Skill use work - ICT - Internet - How often - For mail  =  object
['Every day' 'Less than once a month'
 'Less than once a week but at least once a month'
 'Not stated or inferred' 'Never' 'At least once a week but not every day']

Col:  LNG_HOME  =  object
['Japanese' 'Not stated or inferred' 'Korean' 'Thai' 'Zhuang; Chuang'
 'Russian' 'Kazakh' 'Tatar' 'Azerbaijani' 'Kirghiz; Kyrgyz'
 'Uighur; Uyghur' 'Turkish' 'Uzbek']

Col:  Skill use everyday life - ICT - Computer - How often - Spreadsheets  =  object
['Less than once a week but at least once a month'
 'Less than once a month' 'At least once a week but not every day' 'Never'
 'Not stated or inferred' 'Every day']

Col:  NFEHRS  =  object
['880' '24' '100' 'Not stated or inferred' '1000' '1200' '20' '32' '96'
 '160' '40' '1920' '5' '16' '56' '10' '2' '192' '80' '480' '21' '6' '4'
 '15' '8' '30' '120' '64' '7' '112' '200' '50' '104' '288' '3' '144' '12'
 '48' '600' '1600' '320' '9' '1400' '1640' '14' '800' '400' '720' '1' '18'
 '240' '1280' '1120' '90' '72' '960' '36' '128' '640' '66' '520' '1440'
 '17' '45' '280' '60' '140' '384' '65' '150' '820' '560' '224' '35' '300'
 '168' '83' '304' '26' '1760' '54' '352' '136' '101' '176' '86' '27' '22'
 '11' '1520' '47' '88' '70' '1680' '500' '74' '468' '184' '360' '132'
 '776' '768' '55' '1040' '138' '135' '680' '474' '840' '75' '416' '784'
 '34' '276' '57' '1344' '290' '201' '51' '99' '1800' '1080' '25' '968'
 '760' '256' '208' '357' '29' '1480' '134' '864' '250' '440' '248' '368'
 '344' '264' '1864' '1320' '206' '978' '93' '180' '1248' '210' '38' '118'
 '576' '108' '44' '816' '98' '87' '58' '94' '230' '84' '115' '700' '43'
 '448' '13' '832' '170' '130' '46' '992' '92' '152' '216' '158' '23' '552'
 '1456' '106' '432' '255' '528' '114' '76' '124' '49' '1152' '52' '59'
 '131' '77' '156' '39' '225' '365' '28' '234' '42' '1736' '750' '41' '116'
 '33' '53' '19']

Col:  ISCO2C  =  object
['Personal service workers'
 'Information and communications technology professionals'
 'Administrative and commercial managers' 'Sales workers'
 'Health associate professionals'
 'Metal, machinery and related trades workers' 'Teaching professionals'
 'General and keyboard clerks'
 'Business and administration associate professionals'
 'Personal care workers' 'Market-oriented skilled agricultural workers'
 'Science and engineering associate professionals'
 'Handicraft and printing workers'
 'Stationary plant and machine operators'
 'Production and specialised services managers'
 'Labourers in mining, construction, manufacturing and transport'
 'Drivers and mobile plant operators'
 'Food processing, wood working, garment and other craft and related trades workers'
 'Health professionals' 'Legal, social and cultural professionals'
 'Legal, social, cultural and related associate professionals'
 'Business and administration professionals' 'Customer services clerks'
 'Protective services workers'
 'Chief executives, senior officials and legislators' 'Assemblers'
 'Hospitality, retail and other services managers'
 'Building and related trades workers, excluding electricians'
 'Electrical and electronic trades workers' 'Food preparation assistants'
 'Science and engineering professionals'
 'Numerical and material recording clerks'
 'Information and communications technicians'
 'Other clerical support workers' 'Cleaners and helpers'
 'No paid work for past 5 years' 'Refused' "Don't know"
 'Non-commissioned armed forces officers'
 'Armed forces occupations, other ranks'
 'Refuse workers and other elementary workers'
 'Agricultural, forestry and fishery labourers'
 'Market-oriented skilled forestry, fishery and hunting workers'
 'Commissioned armed forces officers' 'Professionals'
 'Not stated or inferred' 'Street and related sales and service workers'
 'Managers' 'Subsistence farmers, fishers, hunters and gatherers'
 'Technicians and associate professionals' 'Valid skip']

Col:  VET  =  object
['Not stated or inferred' 'True' 'False']

Col:  Skill use work - ICT - Experience with computer in job  =  object
['Yes' 'No']

Col:  Skill use everyday life - ICT - Computer - How often - Real-time discussions  =  object
['Never' 'Less than once a week but at least once a month'
 'At least once a week but not every day' 'Less than once a month'
 'Not stated or inferred' 'Every day']

Col:  ISCOSKIL4  =  object
['Semi-skilled white-collar occupations' 'Skilled occupations'
 'Semi-skilled blue-collar occupations' 'Elementary occupations'
 'Not stated or inferred']

Col:  Skill use work - ICT - Internet - How often - Conduct transactions  =  object
['Every day' 'Never' 'Less than once a month' 'Not stated or inferred'
 'Less than once a week but at least once a month'
 'At least once a week but not every day']

Col:  NFEHRSJR  =  object
['880' '24' '0' 'Not stated or inferred' '1000' '1200' '20' '32' '96'
 '160' '18' '40' '1920' '5' '12' '56' '2.5' '2' '192' '16' '360' '5.25'
 '80' '8' '4' '15' '30' '6' '90' '240' '64' '10' '7' '100' '112' '200'
 '37.5' '120' '78' '288' '7.5' '3' '144' '48' '600' '1600' '320' '9' '480'
 '410' '14' '400' '36' '22.5' '0.75' '720' '1' '2.25' '42' '60' '1280'
 '12.5' '1120' '72' '960' '1.25' '128' '50' '130' '1440' '8.5' '45' '280'
 '800' '3.75' '900' '25' '140' '4.5' '11.25' '520' '216' '65' '150' '615'
 '560' '0.5' '26' '35' '300' '168' '640' '83' '1.5' '105' '180' '440'
 '1.75' '54' '352' '136' '750' '101' '86' '13.5' '5.5' '132' '11' '1140'
 '390' '47' '66' '3.5' '70' '27' '1680' '500' '74' '28' '75' '468' '225'
 '184' '384' '582' '768' '55' '126' '260' '103.5' '135' '170' '118.5'
 '112.5' '22' '450' '840' '88' '392' '25.5' '207' '14.25' '1344' '145'
 '150.75' '12.75' '49.5' '250' '67.5' '1800' '540' '10.5' '6.75' '242'
 '104' '1400' '256' '208' '357' '41.25' '7.25' '680' '780' '34' '33.5'
 '21' '18.75' '62' '172' '510' '264' '102' '466' '420' '270' '330' '103'
 '416' '978' '93' '6.5' '936' '26.25' '248' '210' '28.5' '118' '81' '33'
 '612' '49' '84' '157.5' '87' '29' '17' '115' '1760' '1080' '8.25' '700'
 '52.5' '43' '448' '9.75' '125' '176' '1260' '16.5' '40.5' '38' '97.5'
 '34.5' '1350' '92' '832' '114' '68' '1520' '39.5' '414' '1456' '106'
 '432' '0.25' '108' '191.25' '528' '124' '11.5' '15.75' '1320' '20.25'
 '36.75' '32.25' '576' '59' '39' '32.75' '57.75' '760' '156' '1152'
 '168.75' '365' '58.5' '187.5' '1736' '175.5' '17.5' '41' '52' '44' '220'
 '1248' '152' '13.25' '224' '19']

Col:  Skill use work - How often - Using hands or fingers  =  object
['Less than once a month' 'Never'
 'Less than once a week but at least once a month'
 'At least once a week but not every day' 'Every day'
 'Not stated or inferred']

Col:  AGE_R  =  object
[48 47 58 24 32 45 61 30 46 64 29 54 50 36 40 42 44 35 33 49 34 22 59 38
 56 20 55 23 19 25 52 26 53 39 37 57 62 27 43 18 41 28 63 21 31 60 51 65
 17 16 '36' '33' '48' '22' '27' '34' '24' '31' '21' '45' '29' '37' '28'
 '35' '25' '39' '26' '55' '32' '54' '47' '38' '17' '50'
 'Not stated or inferred']

Col:  PVPSL5  =  float64
[320.26748 307.90423 293.1329  ... 250.4867  190.70999 174.72456]

Col:  Skill use work - ICT - Computer - Got the skills needed  =  object
['Yes' 'No' 'Not stated or inferred']

Col:  Skill use work - How often - Negotiating with people  =  object
['Less than once a week but at least once a month' 'Every day'
 'Less than once a month' 'Never' 'At least once a week but not every day'
 'Not stated or inferred']

Col:  Background - Born in country  =  object
['Yes' 'No']

Col:  Current work - Managing other employees - Count  =  object
['1 to 5 people' '6 to 10 people' 'Not stated or inferred'
 '11 to 24 people' '25 to 99 people' '100 or more people']

Col:  NATIVESPEAKER  =  object
['Yes' 'No']

Col:  Current work - Economic sector  =  object
['The private sector (for example a company)'
 'A non-profit organisation (for example a charity, professional association or religious organisation)'
 'The public sector (for example the local government or a state school)'
 'Not stated or inferred']

Col:  Skill use work - How often - Planning own activities  =  object
['At least once a week but not every day' 'Every day' 'Never'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred']

Col:  Current status/work history - Current - Paid job or family business (DERIVED BY CAPI)  =  object
['Yes, paid work one job or business'
 'Yes, paid work more than one job or business or number of jobs/businesses missing'
 'Yes, unpaid work for family business']

Col:  Skill use work - Problem solving - Simple problems  =  object
['At least once a week but not every day' 'Every day' 'Never'
 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred']

Col:  Skill use work - How often - Advising people  =  object
['Less than once a week but at least once a month' 'Every day'
 'Less than once a month' 'Never' 'At least once a week but not every day'
 'Not stated or inferred']

Col:  Skill use work - ICT - Computer - Level of computer use  =  object
['Moderate' 'Complex' 'Straightforward' 'Not stated or inferred']

Col:  Skill use everyday life - ICT - Ever used computer  =  object
['Not stated or inferred' 'Yes']

Col:  NFEHRSNJR  =  object
['880' '0' '100' 'Not stated or inferred' '1000' '6' '1920' '4' '7.5' '2'
 '80' '160' '16' '120' '15.75' '8' '5' '15' '32' '30' '240' '12' '40' '7'
 '24' '200' '12.5' '18' '26' '288' '2.5' '600' '1600' '320' '480' '1400'
 '1230' '14' '800' '20' '48' '2.25' '1' '0.75' '1.75' '37.5' '1120' '10'
 '56' '3' '72' '960' '3.75' '128' '50' '360' '66' '390' '1440' '8.5' '280'
 '60' '144' '1.25' '300' '75' '96' '180' '1.5' '400' '216' '384' '520'
 '205' '560' '224' '78' '1200' '9' '168' '112' '45' '304' '192' '4.5' '35'
 '1320' '5.25' '42' '250' '36' '176' '13.5' '90' '16.5' '44' '11' '140'
 '380' '130' '22' '10.5' '70' '450' '500' '900' '640' '150' '28' '11.25'
 '720' '225' '352' '270' '420' '194' '768' '780' '34.5' '25' '510' '355.5'
 '840' '88' '416' '392' '69' '0.5' '42.75' '145' '50.25' '38.25' '49.5'
 '750' '22.5' '136' '540' '3.5' '726' '760' '256' '208' '13.75' '21.75'
 '680' '1480' '260' '102' '100.5' '648' '56.25' '440' '186' '184' '172'
 '170' '27' '34' '1398' '1260' '990' '103' '210' '19.5' '312' '8.75' '248'
 '9.5' '576' '810' '204' '49' '52.5' '29' '47' '230' '63' '112.5' '115'
 '1280' '105' '2.75' '17.5' '3.25' '832' '125' '84' '5.5' '33.75' '32.5'
 '11.5' '64' '1350' '992' '38' '68' '1520' '118.5' '104' '23' '138' '1456'
 '126' '106' '135' '6.25' '108' '63.75' '114' '1760' '6.75' '0.25' '12.25'
 '10.75' '54' '13' '98.25' '19.25' '17' '156' '1152' '175.5' '62.5'
 '562.5' '58.5' '67.5' '220' '52' '39.75']

Col:  PVPSL1  =  float64
[319.19725 332.87631 366.30684 ... 239.6456  220.71721 206.94565]

Col:  Current work - Managing other employees  =  object
['Yes' 'No' 'Not stated or inferred']

Col:  Skill use everyday life - ICT - Internet - How often - Conduct transactions  =  object
['Never' 'Less than once a month' 'Every day'
 'Less than once a week but at least once a month'
 'At least once a week but not every day' 'Not stated or inferred']

Col:  About yourself - Health - State  =  object
['Fair' 'Good' 'Very good' 'Excellent' 'Poor' 'Not stated or inferred']

Col:  PVPSL3  =  float64
[308.83653 316.14523 318.85542 ... 253.2573  203.63768 201.99786]

Col:  Skill use work - Not challenged enough  =  object
['Yes' 'Not stated or inferred' 'No']

Col:  Education - Formal qualification - Reason job related  =  object
['Not stated or inferred' 'Yes' 'No']

Col:  Skill use work - Problem solving - Complex problems  =  object
['Less than once a month' 'At least once a week but not every day'
 'Every day' 'Less than once a week but at least once a month' 'Never'
 'Not stated or inferred']

Col:  Skill use work - ICT - Internet - How often - Work related info  =  object
['Every day' 'At least once a week but not every day'
 'Less than once a month'
 'Less than once a week but at least once a month'
 'Not stated or inferred' 'Never']

Col:  Skill use everyday life - ICT - Experience with computer everyday life  =  object
['Yes' 'No' 'Not stated or inferred']

Col:  PVPSL7  =  float64
[286.01639 329.34613 294.12734 ... 267.84257 205.78928 175.40028]

Col:  Skill use everyday life - ICT - Computer - How often - Programming language  =  object
['Never' 'Less than once a week but at least once a month'
 'Less than once a month' 'Not stated or inferred' 'Every day'
 'At least once a week but not every day']

Col:  PVPSL2  =  float64
[300.98157 303.48002 323.62617 ... 230.2905  198.42781 199.94382]

Col:  Education - Formal qualification - Employed - Useful for job  =  object
['Not stated or inferred' 'Somewhat useful' 'Not useful at all'
 'Very useful' 'Moderately useful']

Col:  Background - Father/male guardian - Highest level of education  =  object
['ISCED 3 (excluding 3C short) and 4' 'ISCED 5 and 6'
 'ISCED 1, 2, and 3C short' 'Not stated or inferred']

Col:  Current work - Hours/week  =  int64
[ 60  50  25  30  59  40  24  54  71  14  45  55  48  35  20   6  65  47
  33   3   7   8  44  18  10  15  70  22  16  21  43  39  42  27  38  37

In [45]:
df_sorted = df_num.copy()

df_sorted.to_csv('data_sorted.csv', index=False)

df_sorted.shape

(11470, 93)